// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryPlus.Data.Context;

#nullable disable

namespace QueryPlus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810020613_MakeJobScriptPathNullable")]
    partial class MakeJobScriptPathNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueryPlus.Domain.Entities.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdCategory")
                        .HasName("pk_category");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("uq_category_description");

                    b.ToTable("tb_category", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.CategoryAud", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    b.Property<int>("IdRevision")
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<byte?>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdCategory", "IdRevision")
                        .HasName("pk_category_aud");

                    b.HasIndex("IdRevision");

                    b.HasIndex("IdRevisionType");

                    b.ToTable("tb_category_aud", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ExecutionLog", b =>
                {
                    b.Property<int>("IdExecutionLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_execution_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExecutionLog"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("DefaultConnection")
                        .HasColumnName("connection_name");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("ExecutionEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("execution_end");

                    b.Property<DateTime>("ExecutionStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("execution_start")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("ParameterValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parameter_values");

                    b.Property<int?>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("IdExecutionLog")
                        .HasName("pk_execution_log");

                    b.HasIndex("ExecutionStart")
                        .IsDescending()
                        .HasDatabaseName("ix_execution_log_date");

                    b.HasIndex("IdProcedure", "ExecutionStart")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_execution_log_proc_date");

                    b.HasIndex("Username", "ExecutionStart")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_execution_log_user_date");

                    b.ToTable("tb_execution_log", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobDefinition", b =>
                {
                    b.Property<int>("IdJobDefinition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_job_definition");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJobDefinition"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("job_type");

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("max_duration_minutes");

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("int")
                        .HasColumnName("memory_limit_mb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NotifyEmails")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notify_emails");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RunAsUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("run_as_user");

                    b.Property<string>("ScriptPath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("script_path");

                    b.Property<string>("ScriptSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("script_sha256");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdJobDefinition")
                        .HasName("pk_job_definition");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_job_definition_name");

                    b.HasIndex("ApprovalStatus", "Enabled")
                        .HasDatabaseName("ix_job_definition_approved_enabled");

                    b.ToTable("tb_job_definition", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_definition_no_self_approval", "[approved_by] IS NULL OR [approved_by] <> [created_by]");
                        });
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobDefinitionAud", b =>
                {
                    b.Property<int>("IdJobDefinition")
                        .HasColumnType("int")
                        .HasColumnName("id_job_definition");

                    b.Property<int>("IdRevision")
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<byte?>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<string>("JobType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("job_type");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("max_duration_minutes");

                    b.Property<int?>("MemoryLimitMb")
                        .HasColumnType("int")
                        .HasColumnName("memory_limit_mb");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NotifyEmails")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notify_emails");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RunAsUser")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("run_as_user");

                    b.Property<string>("ScriptPath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("script_path");

                    b.Property<string>("ScriptSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("script_sha256");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdJobDefinition", "IdRevision")
                        .HasName("pk_job_definition_aud");

                    b.HasIndex("IdRevision");

                    b.HasIndex("IdRevisionType");

                    b.ToTable("tb_job_definition_aud", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobRun", b =>
                {
                    b.Property<int>("IdJobRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_job_run");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJobRun"));

                    b.Property<int?>("ChildPid")
                        .HasColumnType("int")
                        .HasColumnName("child_pid");

                    b.Property<DateTime?>("ChildStartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("child_started_at_utc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int")
                        .HasColumnName("exit_code");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("HostMachine")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("host_machine");

                    b.Property<int>("IdJobDefinition")
                        .HasColumnType("int")
                        .HasColumnName("id_job_definition");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<int?>("RunnerPid")
                        .HasColumnType("int")
                        .HasColumnName("runner_pid");

                    b.Property<DateTime?>("RunnerStartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("runner_started_at_utc");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StderrPath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("stderr_path");

                    b.Property<string>("StdoutPath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("stdout_path");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("triggered_by");

                    b.HasKey("IdJobRun")
                        .HasName("pk_job_run");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_run_status");

                    b.HasIndex("IdJobDefinition", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_job_run_job_definition_started");

                    b.ToTable("tb_job_run", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobRunRequest", b =>
                {
                    b.Property<int>("IdJobRunRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_job_run_request");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJobRunRequest"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("consumed_at");

                    b.Property<int>("IdJobDefinition")
                        .HasColumnType("int")
                        .HasColumnName("id_job_definition");

                    b.Property<int?>("IdJobRun")
                        .HasColumnType("int")
                        .HasColumnName("id_job_run");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requested_by");

                    b.HasKey("IdJobRunRequest")
                        .HasName("pk_job_run_request");

                    b.HasIndex("ConsumedAt")
                        .HasDatabaseName("ix_job_run_request_pending")
                        .HasFilter("[consumed_at] IS NULL");

                    b.HasIndex("IdJobDefinition");

                    b.HasIndex("IdJobRun")
                        .IsUnique()
                        .HasFilter("[id_job_run] IS NOT NULL");

                    b.ToTable("tb_job_run_request", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Procedure", b =>
                {
                    b.Property<int>("IdProcedure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcedure"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("caption");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("DefaultConnection")
                        .HasColumnName("connection_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("database_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("procedure_name");

                    b.Property<string>("RoleEntitlement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_entitlement");

                    b.Property<bool>("SupportsPagination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_pagination");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdProcedure")
                        .HasName("pk_procedure");

                    b.HasIndex("Caption")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_caption");

                    b.HasIndex("IdCategory");

                    b.HasIndex("ConnectionName", "DatabaseName", "ProcedureName")
                        .IsUnique()
                        .HasDatabaseName("uq_procedure_db_proc");

                    b.ToTable("tb_procedure", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureAud", b =>
                {
                    b.Property<int>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<int>("IdRevision")
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("caption");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("connection_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("database_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    b.Property<byte?>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<string>("ProcedureName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("procedure_name");

                    b.Property<string>("RoleEntitlement")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_entitlement");

                    b.Property<bool?>("SupportsPagination")
                        .HasColumnType("bit")
                        .HasColumnName("supports_pagination");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdProcedure", "IdRevision")
                        .HasName("pk_procedure_aud");

                    b.HasIndex("IdRevision");

                    b.HasIndex("IdRevisionType");

                    b.ToTable("tb_procedure_aud", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureColumn", b =>
                {
                    b.Property<int>("IdProcedureColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_procedure_column");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcedureColumn"));

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Left")
                        .HasColumnName("alignment");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FormatMask")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("format_mask");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("technical_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("visible");

                    b.HasKey("IdProcedureColumn")
                        .HasName("pk_procedure_column");

                    b.HasIndex("IdProcedure", "TechnicalName")
                        .IsUnique()
                        .HasDatabaseName("uq_column_procedure_tech");

                    b.ToTable("tb_procedure_column", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureColumnAud", b =>
                {
                    b.Property<int>("IdProcedureColumn")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure_column");

                    b.Property<int>("IdRevision")
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    b.Property<string>("Alignment")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("alignment");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("caption");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FormatMask")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("format_mask");

                    b.Property<int?>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<byte?>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<string>("TechnicalName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("technical_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("IdProcedureColumn", "IdRevision")
                        .HasName("pk_column_aud");

                    b.HasIndex("IdRevision");

                    b.HasIndex("IdRevisionType");

                    b.ToTable("tb_procedure_column_aud", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureParameter", b =>
                {
                    b.Property<int>("IdProcedureParameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_procedure_parameter");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcedureParameter"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("caption");

                    b.Property<string>("ComboValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("combo_values");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("default_value");

                    b.Property<int>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("parameter_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdProcedureParameter")
                        .HasName("pk_procedure_parameter");

                    b.HasIndex("IdProcedure", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_parameter_procedure_name");

                    b.ToTable("tb_procedure_parameter", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureParameterAud", b =>
                {
                    b.Property<int>("IdProcedureParameter")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure_parameter");

                    b.Property<int>("IdRevision")
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("caption");

                    b.Property<string>("ComboValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("combo_values");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("default_value");

                    b.Property<int?>("IdProcedure")
                        .HasColumnType("int")
                        .HasColumnName("id_procedure");

                    b.Property<byte?>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<bool?>("IsSensitive")
                        .HasColumnType("bit")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("ParameterType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("parameter_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdProcedureParameter", "IdRevision")
                        .HasName("pk_parameter_aud");

                    b.HasIndex("IdRevision");

                    b.HasIndex("IdRevisionType");

                    b.ToTable("tb_procedure_parameter_aud", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Revision", b =>
                {
                    b.Property<int>("IdRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_revision");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRevision"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("RevisionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("revision_timestamp")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("IdRevision")
                        .HasName("pk_revision");

                    b.ToTable("tb_revision", (string)null);
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.RevisionType", b =>
                {
                    b.Property<byte>("IdRevisionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_revision_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.HasKey("IdRevisionType")
                        .HasName("pk_revision_type");

                    b.ToTable("tb_revision_type", (string)null);

                    b.HasData(
                        new
                        {
                            IdRevisionType = (byte)1,
                            Description = "INSERT"
                        },
                        new
                        {
                            IdRevisionType = (byte)2,
                            Description = "UPDATE"
                        },
                        new
                        {
                            IdRevisionType = (byte)3,
                            Description = "DELETE"
                        });
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.CategoryAud", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Revision", "Revision")
                        .WithMany("CategoryAudits")
                        .HasForeignKey("IdRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_aud_revision");

                    b.HasOne("QueryPlus.Domain.Entities.RevisionType", "RevisionType")
                        .WithMany()
                        .HasForeignKey("IdRevisionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_aud_revision_type");

                    b.Navigation("Revision");

                    b.Navigation("RevisionType");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ExecutionLog", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Procedure", "Procedure")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_procedure");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobDefinitionAud", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Revision", "Revision")
                        .WithMany("JobDefinitionAudits")
                        .HasForeignKey("IdRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_definition_aud_revision");

                    b.HasOne("QueryPlus.Domain.Entities.RevisionType", "RevisionType")
                        .WithMany()
                        .HasForeignKey("IdRevisionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_job_definition_aud_revision_type");

                    b.Navigation("Revision");

                    b.Navigation("RevisionType");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobRun", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.JobDefinition", "JobDefinition")
                        .WithMany("JobRuns")
                        .HasForeignKey("IdJobDefinition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_run_job_definition");

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobRunRequest", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.JobDefinition", "JobDefinition")
                        .WithMany("JobRunRequests")
                        .HasForeignKey("IdJobDefinition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_run_request_job_definition");

                    b.HasOne("QueryPlus.Domain.Entities.JobRun", "JobRun")
                        .WithOne()
                        .HasForeignKey("QueryPlus.Domain.Entities.JobRunRequest", "IdJobRun")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_run_request_job_run");

                    b.Navigation("JobDefinition");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Procedure", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Category", "Category")
                        .WithMany("Procedures")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureAud", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Revision", "Revision")
                        .WithMany("ProcedureAudits")
                        .HasForeignKey("IdRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_aud_revision");

                    b.HasOne("QueryPlus.Domain.Entities.RevisionType", "RevisionType")
                        .WithMany()
                        .HasForeignKey("IdRevisionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_procedure_aud_revision_type");

                    b.Navigation("Revision");

                    b.Navigation("RevisionType");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureColumn", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Procedure", "Procedure")
                        .WithMany("Columns")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_column_procedure");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureColumnAud", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Revision", "Revision")
                        .WithMany("ProcedureColumnAudits")
                        .HasForeignKey("IdRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_column_aud_revision");

                    b.HasOne("QueryPlus.Domain.Entities.RevisionType", "RevisionType")
                        .WithMany()
                        .HasForeignKey("IdRevisionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_column_aud_revision_type");

                    b.Navigation("Revision");

                    b.Navigation("RevisionType");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureParameter", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Procedure", "Procedure")
                        .WithMany("Parameters")
                        .HasForeignKey("IdProcedure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parameter_procedure");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.ProcedureParameterAud", b =>
                {
                    b.HasOne("QueryPlus.Domain.Entities.Revision", "Revision")
                        .WithMany("ProcedureParameterAudits")
                        .HasForeignKey("IdRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parameter_aud_revision");

                    b.HasOne("QueryPlus.Domain.Entities.RevisionType", "RevisionType")
                        .WithMany()
                        .HasForeignKey("IdRevisionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parameter_aud_revision_type");

                    b.Navigation("Revision");

                    b.Navigation("RevisionType");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Category", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.JobDefinition", b =>
                {
                    b.Navigation("JobRunRequests");

                    b.Navigation("JobRuns");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Procedure", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("QueryPlus.Domain.Entities.Revision", b =>
                {
                    b.Navigation("CategoryAudits");

                    b.Navigation("JobDefinitionAudits");

                    b.Navigation("ProcedureAudits");

                    b.Navigation("ProcedureColumnAudits");

                    b.Navigation("ProcedureParameterAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
